# -*- coding: utf-8 -*-
"""newkeras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNJ5MHa982vjs8SIvqie-kT7PXQ3Pzrw
"""

from google.colab import drive
drive.mount('/content/drive')

!git clone https://github.com/kentaroy47/frcnn-from-scratch-with-keras.git

# Commented out IPython magic to ensure Python compatibility.
# %cd frcnn-from-scratch-with-keras

!pip install -r requirements.txt

!mkdir pretrain & mv pretrain

!wget https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels.h5

!python train_rpn.py --network vgg -o simple -p /content/drive/My\ Drive/annotate.txt

!python train_frcnn.py --network vgg -o simple -p /content/drive/My\ Drive/annotate.txt --rpn models/rpn/rpn.vgg.weights.36-1.42.hdf5

!python train_frcnn.py --network vgg16 -o simple -p /content/drive/My\ Drive/annotate.txt --load /content/drive/My\ Drive/keras-frcnn/model_frcnn.hdf5.